[2020-11-17 23:43:06,978][ERROR][3533423][experiments.py:run_experiment_from_to_file:752] XXX failed 19 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1204, agent_id=19, malfunction_duration=50). Found earliest=1205 for Waypoint(position=(88, 22), direction=2)
[2020-11-17 23:43:06,978][ERROR][3533423][experiments.py:run_experiment_from_to_file:752] XXX failed 19 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1204, agent_id=19, malfunction_duration=50). Found earliest=1205 for Waypoint(position=(88, 22), direction=2)
[2020-11-17 23:55:08,625][ERROR][3544140][experiments.py:run_experiment_from_to_file:752] XXX failed 93 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=801, agent_id=43, malfunction_duration=50). Found earliest=802 for Waypoint(position=(22, 28), direction=1)
[2020-11-17 23:55:08,625][ERROR][3544140][experiments.py:run_experiment_from_to_file:752] XXX failed 93 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=801, agent_id=43, malfunction_duration=50). Found earliest=802 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 00:05:47,440][ERROR][3551605][experiments.py:run_experiment_from_to_file:752] XXX failed 131 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1310, agent_id=19, malfunction_duration=50). Found earliest=1311 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 00:05:47,440][ERROR][3551605][experiments.py:run_experiment_from_to_file:752] XXX failed 131 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1310, agent_id=19, malfunction_duration=50). Found earliest=1311 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 00:15:51,651][ERROR][3556600][experiments.py:run_experiment_from_to_file:752] XXX failed 163 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=587, agent_id=51, malfunction_duration=50). Found earliest=588 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 00:15:51,651][ERROR][3556600][experiments.py:run_experiment_from_to_file:752] XXX failed 163 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=587, agent_id=51, malfunction_duration=50). Found earliest=588 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 00:33:47,382][ERROR][3562844][experiments.py:run_experiment_from_to_file:752] XXX failed 203 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 00:33:47,382][ERROR][3562844][experiments.py:run_experiment_from_to_file:752] XXX failed 203 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 00:34:09,889][ERROR][3562980][experiments.py:run_experiment_from_to_file:752] XXX failed 205 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 00:34:09,889][ERROR][3562980][experiments.py:run_experiment_from_to_file:752] XXX failed 205 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 00:47:49,273][ERROR][3570321][experiments.py:run_experiment_from_to_file:752] XXX failed 251 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1168, agent_id=65, malfunction_duration=50). Found earliest=1169 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 00:47:49,273][ERROR][3570321][experiments.py:run_experiment_from_to_file:752] XXX failed 251 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1168, agent_id=65, malfunction_duration=50). Found earliest=1169 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 00:56:26,464][ERROR][3572285][experiments.py:run_experiment_from_to_file:752] XXX failed 263 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 00:56:26,464][ERROR][3572285][experiments.py:run_experiment_from_to_file:752] XXX failed 263 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 01:00:45,829][ERROR][3579313][experiments.py:run_experiment_from_to_file:752] XXX failed 291 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=255, agent_id=19, malfunction_duration=50). Found earliest=256 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 01:00:45,829][ERROR][3579313][experiments.py:run_experiment_from_to_file:752] XXX failed 291 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=255, agent_id=19, malfunction_duration=50). Found earliest=256 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 01:12:35,955][ERROR][3587520][experiments.py:run_experiment_from_to_file:752] XXX failed 340 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 01:12:35,955][ERROR][3587520][experiments.py:run_experiment_from_to_file:752] XXX failed 340 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 01:14:53,989][ERROR][3590684][experiments.py:run_experiment_from_to_file:752] XXX failed 365 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=676, agent_id=43, malfunction_duration=50). Found earliest=677 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 01:14:53,989][ERROR][3590684][experiments.py:run_experiment_from_to_file:752] XXX failed 365 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=676, agent_id=43, malfunction_duration=50). Found earliest=677 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 01:25:58,849][ERROR][3597588][experiments.py:run_experiment_from_to_file:752] XXX failed 403 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=453, agent_id=19, malfunction_duration=50). Found earliest=454 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 01:25:58,849][ERROR][3597588][experiments.py:run_experiment_from_to_file:752] XXX failed 403 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=453, agent_id=19, malfunction_duration=50). Found earliest=454 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 01:36:40,384][ERROR][3603410][experiments.py:run_experiment_from_to_file:752] XXX failed 435 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=1042, agent_id=51, malfunction_duration=50). Found earliest=1043 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 01:36:40,384][ERROR][3603410][experiments.py:run_experiment_from_to_file:752] XXX failed 435 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=1042, agent_id=51, malfunction_duration=50). Found earliest=1043 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 02:11:45,921][ERROR][3621469][experiments.py:run_experiment_from_to_file:752] XXX failed 523 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=819, agent_id=65, malfunction_duration=50). Found earliest=820 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 02:11:45,921][ERROR][3621469][experiments.py:run_experiment_from_to_file:752] XXX failed 523 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=819, agent_id=65, malfunction_duration=50). Found earliest=820 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 02:22:33,305][ERROR][3624324][experiments.py:run_experiment_from_to_file:752] XXX failed 542 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:22:33,305][ERROR][3624324][experiments.py:run_experiment_from_to_file:752] XXX failed 542 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:23:17,319][ERROR][3625886][experiments.py:run_experiment_from_to_file:752] XXX failed 550 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 02:23:17,319][ERROR][3625886][experiments.py:run_experiment_from_to_file:752] XXX failed 550 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 02:23:28,469][ERROR][3627522][experiments.py:run_experiment_from_to_file:752] XXX failed 563 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=473, agent_id=19, malfunction_duration=50). Found earliest=474 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 02:23:28,469][ERROR][3627522][experiments.py:run_experiment_from_to_file:752] XXX failed 563 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=473, agent_id=19, malfunction_duration=50). Found earliest=474 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 02:23:59,282][ERROR][3626608][experiments.py:run_experiment_from_to_file:752] XXX failed 555 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:23:59,282][ERROR][3626608][experiments.py:run_experiment_from_to_file:752] XXX failed 555 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:26:27,201][ERROR][3628191][experiments.py:run_experiment_from_to_file:752] XXX failed 572 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:26:27,201][ERROR][3628191][experiments.py:run_experiment_from_to_file:752] XXX failed 572 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:27:52,043][ERROR][3629336][experiments.py:run_experiment_from_to_file:752] XXX failed 576 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:27:52,043][ERROR][3629336][experiments.py:run_experiment_from_to_file:752] XXX failed 576 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 02:29:19,953][ERROR][3630494][experiments.py:run_experiment_from_to_file:752] XXX failed 590 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 02:29:19,953][ERROR][3630494][experiments.py:run_experiment_from_to_file:752] XXX failed 590 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 02:36:30,388][ERROR][3637192][experiments.py:run_experiment_from_to_file:752] XXX failed 637 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=146, agent_id=43, malfunction_duration=50). Found earliest=147 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 02:36:30,388][ERROR][3637192][experiments.py:run_experiment_from_to_file:752] XXX failed 637 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=146, agent_id=43, malfunction_duration=50). Found earliest=147 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 02:44:49,380][ERROR][3641874][experiments.py:run_experiment_from_to_file:752] XXX failed 675 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1574, agent_id=19, malfunction_duration=50). Found earliest=1575 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 02:44:49,380][ERROR][3641874][experiments.py:run_experiment_from_to_file:752] XXX failed 675 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1574, agent_id=19, malfunction_duration=50). Found earliest=1575 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 02:53:59,680][ERROR][3647977][experiments.py:run_experiment_from_to_file:752] XXX failed 707 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=966, agent_id=51, malfunction_duration=50). Found earliest=967 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 02:53:59,680][ERROR][3647977][experiments.py:run_experiment_from_to_file:752] XXX failed 707 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=966, agent_id=51, malfunction_duration=50). Found earliest=967 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 03:03:15,109][ERROR][3651469][experiments.py:run_experiment_from_to_file:752] XXX failed 728 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 03:03:15,109][ERROR][3651469][experiments.py:run_experiment_from_to_file:752] XXX failed 728 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 03:26:31,861][ERROR][3663352][experiments.py:run_experiment_from_to_file:752] XXX failed 795 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1167, agent_id=65, malfunction_duration=50). Found earliest=1168 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 03:26:31,861][ERROR][3663352][experiments.py:run_experiment_from_to_file:752] XXX failed 795 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1167, agent_id=65, malfunction_duration=50). Found earliest=1168 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 03:30:53,134][ERROR][3663150][experiments.py:run_experiment_from_to_file:752] XXX failed 792 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 03:30:53,134][ERROR][3663150][experiments.py:run_experiment_from_to_file:752] XXX failed 792 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 03:40:26,933][ERROR][3669851][experiments.py:run_experiment_from_to_file:752] XXX failed 835 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1426, agent_id=19, malfunction_duration=50). Found earliest=1427 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 03:40:26,933][ERROR][3669851][experiments.py:run_experiment_from_to_file:752] XXX failed 835 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=1426, agent_id=19, malfunction_duration=50). Found earliest=1427 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 03:48:10,653][ERROR][3674361][experiments.py:run_experiment_from_to_file:752] XXX failed 870 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 03:48:10,653][ERROR][3674361][experiments.py:run_experiment_from_to_file:752] XXX failed 870 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 03:52:33,424][ERROR][3679382][experiments.py:run_experiment_from_to_file:752] XXX failed 909 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1025, agent_id=43, malfunction_duration=50). Found earliest=1026 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 03:52:33,424][ERROR][3679382][experiments.py:run_experiment_from_to_file:752] XXX failed 909 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1025, agent_id=43, malfunction_duration=50). Found earliest=1026 for Waypoint(position=(22, 28), direction=1)
[2020-11-18 04:01:11,108][ERROR][3685017][experiments.py:run_experiment_from_to_file:752] XXX failed 947 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=334, agent_id=19, malfunction_duration=50). Found earliest=335 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 04:01:11,108][ERROR][3685017][experiments.py:run_experiment_from_to_file:752] XXX failed 947 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 19 with malfunction ExperimentMalfunction(time_step=334, agent_id=19, malfunction_duration=50). Found earliest=335 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 04:10:02,354][ERROR][3690244][experiments.py:run_experiment_from_to_file:752] XXX failed 979 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=1246, agent_id=51, malfunction_duration=50). Found earliest=1247 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 04:10:02,354][ERROR][3690244][experiments.py:run_experiment_from_to_file:752] XXX failed 979 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 51 with malfunction ExperimentMalfunction(time_step=1246, agent_id=51, malfunction_duration=50). Found earliest=1247 for Waypoint(position=(75, 26), direction=0)
[2020-11-18 04:40:49,862][ERROR][3702585][experiments.py:run_experiment_from_to_file:752] XXX failed 1042 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 04:40:49,862][ERROR][3702585][experiments.py:run_experiment_from_to_file:752] XXX failed 1042 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 04:51:07,654][ERROR][3708087][experiments.py:run_experiment_from_to_file:752] XXX failed 1067 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1292, agent_id=65, malfunction_duration=50). Found earliest=1293 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 04:51:07,654][ERROR][3708087][experiments.py:run_experiment_from_to_file:752] XXX failed 1067 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 65 with malfunction ExperimentMalfunction(time_step=1292, agent_id=65, malfunction_duration=50). Found earliest=1293 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 05:05:21,651][ERROR][3711474][experiments.py:run_experiment_from_to_file:752] XXX failed 1079 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 05:05:21,651][ERROR][3711474][experiments.py:run_experiment_from_to_file:752] XXX failed 1079 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 05:08:13,278][ERROR][3715240][experiments.py:run_experiment_from_to_file:752] XXX failed 1090 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=547, agent_id=2, malfunction_duration=50). Found earliest=548 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:08:13,278][ERROR][3715240][experiments.py:run_experiment_from_to_file:752] XXX failed 1090 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=547, agent_id=2, malfunction_duration=50). Found earliest=548 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:09:27,705][ERROR][3715746][experiments.py:run_experiment_from_to_file:752] XXX failed 1092 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1181, agent_id=4, malfunction_duration=50). Found earliest=1182 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:09:27,705][ERROR][3715746][experiments.py:run_experiment_from_to_file:752] XXX failed 1092 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1181, agent_id=4, malfunction_duration=50). Found earliest=1182 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:10:45,428][ERROR][3716487][experiments.py:run_experiment_from_to_file:752] XXX failed 1098 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1174, agent_id=10, malfunction_duration=50). Found earliest=1175 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:10:45,428][ERROR][3716487][experiments.py:run_experiment_from_to_file:752] XXX failed 1098 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1174, agent_id=10, malfunction_duration=50). Found earliest=1175 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:16:48,839][ERROR][3720489][experiments.py:run_experiment_from_to_file:752] XXX failed 1118 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1167, agent_id=30, malfunction_duration=50). Found earliest=1168 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:16:48,839][ERROR][3720489][experiments.py:run_experiment_from_to_file:752] XXX failed 1118 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1167, agent_id=30, malfunction_duration=50). Found earliest=1168 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:22:29,755][ERROR][3724279][experiments.py:run_experiment_from_to_file:752] XXX failed 1137 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1181, agent_id=49, malfunction_duration=50). Found earliest=1182 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 05:22:29,755][ERROR][3724279][experiments.py:run_experiment_from_to_file:752] XXX failed 1137 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1181, agent_id=49, malfunction_duration=50). Found earliest=1182 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 05:22:44,217][ERROR][3724442][experiments.py:run_experiment_from_to_file:752] XXX failed 1140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=473, agent_id=2, malfunction_duration=50). Found earliest=474 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:22:44,217][ERROR][3724442][experiments.py:run_experiment_from_to_file:752] XXX failed 1140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=473, agent_id=2, malfunction_duration=50). Found earliest=474 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:43:13,257][ERROR][3736194][experiments.py:run_experiment_from_to_file:752] XXX failed 1192 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 05:43:13,257][ERROR][3736194][experiments.py:run_experiment_from_to_file:752] XXX failed 1192 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 05:43:18,720][ERROR][3738137][experiments.py:run_experiment_from_to_file:752] XXX failed 1202 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=560, agent_id=2, malfunction_duration=50). Found earliest=561 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:43:18,720][ERROR][3738137][experiments.py:run_experiment_from_to_file:752] XXX failed 1202 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=560, agent_id=2, malfunction_duration=50). Found earliest=561 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 05:43:24,136][ERROR][3738169][experiments.py:run_experiment_from_to_file:752] XXX failed 1204 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1256, agent_id=4, malfunction_duration=50). Found earliest=1257 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:43:24,136][ERROR][3738169][experiments.py:run_experiment_from_to_file:752] XXX failed 1204 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1256, agent_id=4, malfunction_duration=50). Found earliest=1257 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:45:13,918][ERROR][3739042][experiments.py:run_experiment_from_to_file:752] XXX failed 1210 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1249, agent_id=10, malfunction_duration=50). Found earliest=1250 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:45:13,918][ERROR][3739042][experiments.py:run_experiment_from_to_file:752] XXX failed 1210 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1249, agent_id=10, malfunction_duration=50). Found earliest=1250 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:50:12,350][ERROR][3739310][experiments.py:run_experiment_from_to_file:752] XXX failed 1213 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 05:50:12,350][ERROR][3739310][experiments.py:run_experiment_from_to_file:752] XXX failed 1213 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 05:54:43,525][ERROR][3741020][experiments.py:run_experiment_from_to_file:752] XXX failed 1222 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 05:54:43,525][ERROR][3741020][experiments.py:run_experiment_from_to_file:752] XXX failed 1222 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 05:54:50,709][ERROR][3743344][experiments.py:run_experiment_from_to_file:752] XXX failed 1230 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=548, agent_id=30, malfunction_duration=50). Found earliest=549 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 05:54:50,709][ERROR][3743344][experiments.py:run_experiment_from_to_file:752] XXX failed 1230 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=548, agent_id=30, malfunction_duration=50). Found earliest=549 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 06:04:21,703][ERROR][3747621][experiments.py:run_experiment_from_to_file:752] XXX failed 1243 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1313, agent_id=43, malfunction_duration=50). Found earliest=1314 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 06:04:21,703][ERROR][3747621][experiments.py:run_experiment_from_to_file:752] XXX failed 1243 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1313, agent_id=43, malfunction_duration=50). Found earliest=1314 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 06:06:16,424][ERROR][3694530][experiments.py:run_experiment_from_to_file:752] XXX failed 1007 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 06:06:16,424][ERROR][3694530][experiments.py:run_experiment_from_to_file:752] XXX failed 1007 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 06:43:02,909][ERROR][3762028][experiments.py:run_experiment_from_to_file:752] XXX failed 1274 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 06:43:02,909][ERROR][3762028][experiments.py:run_experiment_from_to_file:752] XXX failed 1274 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 06:52:52,895][ERROR][3767027][experiments.py:run_experiment_from_to_file:752] XXX failed 1292 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=381, agent_id=18, malfunction_duration=50). Found earliest=382 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 06:52:52,895][ERROR][3767027][experiments.py:run_experiment_from_to_file:752] XXX failed 1292 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=381, agent_id=18, malfunction_duration=50). Found earliest=382 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 07:20:24,082][ERROR][3775139][experiments.py:run_experiment_from_to_file:752] XXX failed 1313 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 07:20:24,082][ERROR][3775139][experiments.py:run_experiment_from_to_file:752] XXX failed 1313 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 07:30:55,009][ERROR][3783166][experiments.py:run_experiment_from_to_file:752] XXX failed 1324 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=843, agent_id=50, malfunction_duration=50). Found earliest=844 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 07:30:55,009][ERROR][3783166][experiments.py:run_experiment_from_to_file:752] XXX failed 1324 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=843, agent_id=50, malfunction_duration=50). Found earliest=844 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 08:22:13,227][ERROR][3804677][experiments.py:run_experiment_from_to_file:752] XXX failed 1362 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=188, agent_id=2, malfunction_duration=50). Found earliest=189 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 08:22:13,227][ERROR][3804677][experiments.py:run_experiment_from_to_file:752] XXX failed 1362 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=188, agent_id=2, malfunction_duration=50). Found earliest=189 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 08:22:33,193][ERROR][3804851][experiments.py:run_experiment_from_to_file:752] XXX failed 1364 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1336, agent_id=4, malfunction_duration=50). Found earliest=1337 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:22:33,193][ERROR][3804851][experiments.py:run_experiment_from_to_file:752] XXX failed 1364 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1336, agent_id=4, malfunction_duration=50). Found earliest=1337 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:28:07,260][ERROR][3807766][experiments.py:run_experiment_from_to_file:752] XXX failed 1370 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1329, agent_id=10, malfunction_duration=50). Found earliest=1330 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:28:07,260][ERROR][3807766][experiments.py:run_experiment_from_to_file:752] XXX failed 1370 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1329, agent_id=10, malfunction_duration=50). Found earliest=1330 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:40:14,837][ERROR][3814004][experiments.py:run_experiment_from_to_file:752] XXX failed 1390 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=688, agent_id=30, malfunction_duration=50). Found earliest=689 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:40:14,837][ERROR][3814004][experiments.py:run_experiment_from_to_file:752] XXX failed 1390 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=688, agent_id=30, malfunction_duration=50). Found earliest=689 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 08:46:35,733][ERROR][3815710][experiments.py:run_experiment_from_to_file:752] XXX failed 1399 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 08:46:35,733][ERROR][3815710][experiments.py:run_experiment_from_to_file:752] XXX failed 1399 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 08:48:24,506][ERROR][3816655][experiments.py:run_experiment_from_to_file:752] XXX failed 1400 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 08:48:24,506][ERROR][3816655][experiments.py:run_experiment_from_to_file:752] XXX failed 1400 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 08:49:59,376][ERROR][3818032][experiments.py:run_experiment_from_to_file:752] XXX failed 1409 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1302, agent_id=49, malfunction_duration=50). Found earliest=1303 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 08:49:59,376][ERROR][3818032][experiments.py:run_experiment_from_to_file:752] XXX failed 1409 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1302, agent_id=49, malfunction_duration=50). Found earliest=1303 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 08:50:54,832][ERROR][3818398][experiments.py:run_experiment_from_to_file:752] XXX failed 1412 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=324, agent_id=2, malfunction_duration=50). Found earliest=325 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 08:50:54,832][ERROR][3818398][experiments.py:run_experiment_from_to_file:752] XXX failed 1412 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=324, agent_id=2, malfunction_duration=50). Found earliest=325 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 08:59:10,728][ERROR][3820609][experiments.py:run_experiment_from_to_file:752] XXX failed 1420 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 08:59:10,728][ERROR][3820609][experiments.py:run_experiment_from_to_file:752] XXX failed 1420 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 09:10:15,855][ERROR][3795495][experiments.py:run_experiment_from_to_file:752] XXX failed 1341 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 09:10:15,855][ERROR][3795495][experiments.py:run_experiment_from_to_file:752] XXX failed 1341 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 09:24:59,817][ERROR][3797204][experiments.py:run_experiment_from_to_file:752] XXX failed 1342 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 09:24:59,817][ERROR][3797204][experiments.py:run_experiment_from_to_file:752] XXX failed 1342 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 09:39:37,499][ERROR][3840843][experiments.py:run_experiment_from_to_file:752] XXX failed 1474 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=865, agent_id=2, malfunction_duration=50). Found earliest=866 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 09:39:37,499][ERROR][3840843][experiments.py:run_experiment_from_to_file:752] XXX failed 1474 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=865, agent_id=2, malfunction_duration=50). Found earliest=866 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 09:40:43,314][ERROR][3841407][experiments.py:run_experiment_from_to_file:752] XXX failed 1476 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1355, agent_id=4, malfunction_duration=50). Found earliest=1356 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 09:40:43,314][ERROR][3841407][experiments.py:run_experiment_from_to_file:752] XXX failed 1476 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1355, agent_id=4, malfunction_duration=50). Found earliest=1356 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 09:44:38,489][ERROR][3843496][experiments.py:run_experiment_from_to_file:752] XXX failed 1482 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1348, agent_id=10, malfunction_duration=50). Found earliest=1349 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 09:44:38,489][ERROR][3843496][experiments.py:run_experiment_from_to_file:752] XXX failed 1482 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1348, agent_id=10, malfunction_duration=50). Found earliest=1349 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 09:47:26,730][ERROR][3797547][experiments.py:run_experiment_from_to_file:752] XXX failed 1344 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 09:47:26,730][ERROR][3797547][experiments.py:run_experiment_from_to_file:752] XXX failed 1344 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 10:05:43,843][ERROR][3854004][experiments.py:run_experiment_from_to_file:752] XXX failed 1502 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1297, agent_id=30, malfunction_duration=50). Found earliest=1298 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 10:05:43,843][ERROR][3854004][experiments.py:run_experiment_from_to_file:752] XXX failed 1502 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1297, agent_id=30, malfunction_duration=50). Found earliest=1298 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 10:22:01,822][ERROR][3862136][experiments.py:run_experiment_from_to_file:752] XXX failed 1515 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1119, agent_id=43, malfunction_duration=50). Found earliest=1120 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 10:22:01,822][ERROR][3862136][experiments.py:run_experiment_from_to_file:752] XXX failed 1515 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1119, agent_id=43, malfunction_duration=50). Found earliest=1120 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 10:41:56,464][ERROR][3750589][experiments.py:run_experiment_from_to_file:752] XXX failed 1251 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 10:41:56,464][ERROR][3750589][experiments.py:run_experiment_from_to_file:752] XXX failed 1251 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 10:56:30,503][ERROR][3874822][experiments.py:run_experiment_from_to_file:752] XXX failed 1564 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=140, agent_id=18, malfunction_duration=50). Found earliest=141 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 10:56:30,503][ERROR][3874822][experiments.py:run_experiment_from_to_file:752] XXX failed 1564 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=140, agent_id=18, malfunction_duration=50). Found earliest=141 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 11:22:58,948][ERROR][3885388][experiments.py:run_experiment_from_to_file:752] XXX failed 1596 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=639, agent_id=50, malfunction_duration=50). Found earliest=640 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 11:22:58,948][ERROR][3885388][experiments.py:run_experiment_from_to_file:752] XXX failed 1596 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=639, agent_id=50, malfunction_duration=50). Found earliest=640 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 12:21:21,966][ERROR][3905154][experiments.py:run_experiment_from_to_file:752] XXX failed 1634 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=45, agent_id=2, malfunction_duration=50). Found earliest=46 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 12:21:21,966][ERROR][3905154][experiments.py:run_experiment_from_to_file:752] XXX failed 1634 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=45, agent_id=2, malfunction_duration=50). Found earliest=46 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 12:21:46,444][ERROR][3905287][experiments.py:run_experiment_from_to_file:752] XXX failed 1636 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1533, agent_id=4, malfunction_duration=50). Found earliest=1534 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:21:46,444][ERROR][3905287][experiments.py:run_experiment_from_to_file:752] XXX failed 1636 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1533, agent_id=4, malfunction_duration=50). Found earliest=1534 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:26:28,415][ERROR][3906976][experiments.py:run_experiment_from_to_file:752] XXX failed 1642 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1505, agent_id=10, malfunction_duration=50). Found earliest=1506 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:26:28,415][ERROR][3906976][experiments.py:run_experiment_from_to_file:752] XXX failed 1642 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1505, agent_id=10, malfunction_duration=50). Found earliest=1506 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:43:21,243][ERROR][3915147][experiments.py:run_experiment_from_to_file:752] XXX failed 1662 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1507, agent_id=30, malfunction_duration=50). Found earliest=1508 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:43:21,243][ERROR][3915147][experiments.py:run_experiment_from_to_file:752] XXX failed 1662 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1507, agent_id=30, malfunction_duration=50). Found earliest=1508 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 12:54:23,017][ERROR][3920611][experiments.py:run_experiment_from_to_file:752] XXX failed 1673 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 12:54:23,017][ERROR][3920611][experiments.py:run_experiment_from_to_file:752] XXX failed 1673 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 12:58:31,499][ERROR][3924133][experiments.py:run_experiment_from_to_file:752] XXX failed 1681 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1502, agent_id=49, malfunction_duration=50). Found earliest=1503 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 12:58:31,499][ERROR][3924133][experiments.py:run_experiment_from_to_file:752] XXX failed 1681 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1502, agent_id=49, malfunction_duration=50). Found earliest=1503 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 13:01:22,698][ERROR][3925729][experiments.py:run_experiment_from_to_file:752] XXX failed 1684 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=461, agent_id=2, malfunction_duration=50). Found earliest=462 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 13:01:22,698][ERROR][3925729][experiments.py:run_experiment_from_to_file:752] XXX failed 1684 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=461, agent_id=2, malfunction_duration=50). Found earliest=462 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 13:21:47,194][ERROR][3933875][experiments.py:run_experiment_from_to_file:752] XXX failed 1700 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 13:21:47,194][ERROR][3933875][experiments.py:run_experiment_from_to_file:752] XXX failed 1700 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 13:24:27,678][ERROR][3894853][experiments.py:run_experiment_from_to_file:752] XXX failed 1613 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 13:24:27,678][ERROR][3894853][experiments.py:run_experiment_from_to_file:752] XXX failed 1613 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 13:31:59,577][ERROR][3894446][experiments.py:run_experiment_from_to_file:752] XXX failed 1612 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 13:31:59,577][ERROR][3894446][experiments.py:run_experiment_from_to_file:752] XXX failed 1612 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 13:36:36,211][ERROR][3940231][experiments.py:run_experiment_from_to_file:752] XXX failed 1718 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 13:36:36,211][ERROR][3940231][experiments.py:run_experiment_from_to_file:752] XXX failed 1718 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 13:50:25,708][ERROR][3947980][experiments.py:run_experiment_from_to_file:752] XXX failed 1746 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=339, agent_id=2, malfunction_duration=50). Found earliest=340 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 13:50:25,708][ERROR][3947980][experiments.py:run_experiment_from_to_file:752] XXX failed 1746 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=339, agent_id=2, malfunction_duration=50). Found earliest=340 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 13:51:08,287][ERROR][3948299][experiments.py:run_experiment_from_to_file:752] XXX failed 1748 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1451, agent_id=4, malfunction_duration=50). Found earliest=1452 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 13:51:08,287][ERROR][3948299][experiments.py:run_experiment_from_to_file:752] XXX failed 1748 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1451, agent_id=4, malfunction_duration=50). Found earliest=1452 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 13:54:53,368][ERROR][3949481][experiments.py:run_experiment_from_to_file:752] XXX failed 1754 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1444, agent_id=10, malfunction_duration=50). Found earliest=1445 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 13:54:53,368][ERROR][3949481][experiments.py:run_experiment_from_to_file:752] XXX failed 1754 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1444, agent_id=10, malfunction_duration=50). Found earliest=1445 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 13:58:44,681][ERROR][3739343][experiments.py:run_experiment_from_to_file:752] XXX failed 1215 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 13:58:44,681][ERROR][3739343][experiments.py:run_experiment_from_to_file:752] XXX failed 1215 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:07:40,115][ERROR][3953038][experiments.py:run_experiment_from_to_file:752] XXX failed 1774 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1439, agent_id=30, malfunction_duration=50). Found earliest=1440 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 14:07:40,115][ERROR][3953038][experiments.py:run_experiment_from_to_file:752] XXX failed 1774 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1439, agent_id=30, malfunction_duration=50). Found earliest=1440 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 14:08:24,037][ERROR][3695369][experiments.py:run_experiment_from_to_file:752] XXX failed 1012 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:08:24,037][ERROR][3695369][experiments.py:run_experiment_from_to_file:752] XXX failed 1012 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:12:29,544][ERROR][3953209][experiments.py:run_experiment_from_to_file:752] XXX failed 1777 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 14:12:29,544][ERROR][3953209][experiments.py:run_experiment_from_to_file:752] XXX failed 1777 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 14:13:38,790][ERROR][3773970][experiments.py:run_experiment_from_to_file:752] XXX failed 1309 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:13:38,790][ERROR][3773970][experiments.py:run_experiment_from_to_file:752] XXX failed 1309 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:14:39,847][ERROR][3955911][experiments.py:run_experiment_from_to_file:752] XXX failed 1787 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=512, agent_id=43, malfunction_duration=50). Found earliest=513 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 14:14:39,847][ERROR][3955911][experiments.py:run_experiment_from_to_file:752] XXX failed 1787 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=512, agent_id=43, malfunction_duration=50). Found earliest=513 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 14:27:24,025][ERROR][3887381][experiments.py:run_experiment_from_to_file:752] XXX failed 1599 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:27:24,025][ERROR][3887381][experiments.py:run_experiment_from_to_file:752] XXX failed 1599 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:46:10,279][ERROR][3970521][experiments.py:run_experiment_from_to_file:752] XXX failed 1836 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=1089, agent_id=18, malfunction_duration=50). Found earliest=1090 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 14:46:10,279][ERROR][3970521][experiments.py:run_experiment_from_to_file:752] XXX failed 1836 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=1089, agent_id=18, malfunction_duration=50). Found earliest=1090 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 14:52:09,569][ERROR][3743411][experiments.py:run_experiment_from_to_file:752] XXX failed 1231 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 14:52:09,569][ERROR][3743411][experiments.py:run_experiment_from_to_file:752] XXX failed 1231 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 15:03:38,602][ERROR][3977431][experiments.py:run_experiment_from_to_file:752] XXX failed 1868 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=1502, agent_id=50, malfunction_duration=50). Found earliest=1503 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 15:03:38,602][ERROR][3977431][experiments.py:run_experiment_from_to_file:752] XXX failed 1868 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=1502, agent_id=50, malfunction_duration=50). Found earliest=1503 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 15:19:00,648][ERROR][3884231][experiments.py:run_experiment_from_to_file:752] XXX failed 1590 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 15:19:00,648][ERROR][3884231][experiments.py:run_experiment_from_to_file:752] XXX failed 1590 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 15:22:41,942][ERROR][3743589][experiments.py:run_experiment_from_to_file:752] XXX failed 1232 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 15:22:41,942][ERROR][3743589][experiments.py:run_experiment_from_to_file:752] XXX failed 1232 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 15:25:01,605][ERROR][3985170][experiments.py:run_experiment_from_to_file:752] XXX failed 1906 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=814, agent_id=2, malfunction_duration=50). Found earliest=815 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:25:01,605][ERROR][3985170][experiments.py:run_experiment_from_to_file:752] XXX failed 1906 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=814, agent_id=2, malfunction_duration=50). Found earliest=815 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:25:36,176][ERROR][3985500][experiments.py:run_experiment_from_to_file:752] XXX failed 1908 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1213, agent_id=4, malfunction_duration=50). Found earliest=1214 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:25:36,176][ERROR][3985500][experiments.py:run_experiment_from_to_file:752] XXX failed 1908 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1213, agent_id=4, malfunction_duration=50). Found earliest=1214 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:27:02,033][ERROR][3986338][experiments.py:run_experiment_from_to_file:752] XXX failed 1914 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=811, agent_id=10, malfunction_duration=50). Found earliest=812 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:27:02,033][ERROR][3986338][experiments.py:run_experiment_from_to_file:752] XXX failed 1914 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=811, agent_id=10, malfunction_duration=50). Found earliest=812 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:29:31,667][ERROR][3986512][experiments.py:run_experiment_from_to_file:752] XXX failed 1917 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 15:29:31,667][ERROR][3986512][experiments.py:run_experiment_from_to_file:752] XXX failed 1917 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-18 15:29:32,094][ERROR][3986583][experiments.py:run_experiment_from_to_file:752] XXX failed 1918 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:29:32,094][ERROR][3986583][experiments.py:run_experiment_from_to_file:752] XXX failed 1918 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:30:17,492][ERROR][3988306][experiments.py:run_experiment_from_to_file:752] XXX failed 1934 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=813, agent_id=30, malfunction_duration=50). Found earliest=814 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:30:17,492][ERROR][3988306][experiments.py:run_experiment_from_to_file:752] XXX failed 1934 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=813, agent_id=30, malfunction_duration=50). Found earliest=814 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:34:29,867][ERROR][3992166][experiments.py:run_experiment_from_to_file:752] XXX failed 1953 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1213, agent_id=49, malfunction_duration=50). Found earliest=1214 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 15:34:29,867][ERROR][3992166][experiments.py:run_experiment_from_to_file:752] XXX failed 1953 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 49 with malfunction ExperimentMalfunction(time_step=1213, agent_id=49, malfunction_duration=50). Found earliest=1214 for Waypoint(position=(76, 41), direction=1)
[2020-11-18 15:34:40,075][ERROR][3992278][experiments.py:run_experiment_from_to_file:752] XXX failed 1956 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=347, agent_id=2, malfunction_duration=50). Found earliest=348 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:34:40,075][ERROR][3992278][experiments.py:run_experiment_from_to_file:752] XXX failed 1956 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=347, agent_id=2, malfunction_duration=50). Found earliest=348 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:37:31,357][ERROR][3992375][experiments.py:run_experiment_from_to_file:752] XXX failed 1958 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:37:31,357][ERROR][3992375][experiments.py:run_experiment_from_to_file:752] XXX failed 1958 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:53:24,545][ERROR][4007441][experiments.py:run_experiment_from_to_file:752] XXX failed 2018 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=560, agent_id=2, malfunction_duration=50). Found earliest=561 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:53:24,545][ERROR][4007441][experiments.py:run_experiment_from_to_file:752] XXX failed 2018 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 2 with malfunction ExperimentMalfunction(time_step=560, agent_id=2, malfunction_duration=50). Found earliest=561 for Waypoint(position=(80, 16), direction=3)
[2020-11-18 15:53:30,434][ERROR][4007479][experiments.py:run_experiment_from_to_file:752] XXX failed 2020 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1115, agent_id=4, malfunction_duration=50). Found earliest=1116 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:53:30,434][ERROR][4007479][experiments.py:run_experiment_from_to_file:752] XXX failed 2020 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 4 with malfunction ExperimentMalfunction(time_step=1115, agent_id=4, malfunction_duration=50). Found earliest=1116 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:53:47,212][ERROR][4005912][experiments.py:run_experiment_from_to_file:752] XXX failed 2011 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:53:47,212][ERROR][4005912][experiments.py:run_experiment_from_to_file:752] XXX failed 2011 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 15:54:28,211][ERROR][4007968][experiments.py:run_experiment_from_to_file:752] XXX failed 2026 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1101, agent_id=10, malfunction_duration=50). Found earliest=1102 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 15:54:28,211][ERROR][4007968][experiments.py:run_experiment_from_to_file:752] XXX failed 2026 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 10 with malfunction ExperimentMalfunction(time_step=1101, agent_id=10, malfunction_duration=50). Found earliest=1102 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 16:02:42,197][ERROR][4012415][experiments.py:run_experiment_from_to_file:752] XXX failed 2046 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1108, agent_id=30, malfunction_duration=50). Found earliest=1109 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 16:02:42,197][ERROR][4012415][experiments.py:run_experiment_from_to_file:752] XXX failed 2046 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 30 with malfunction ExperimentMalfunction(time_step=1108, agent_id=30, malfunction_duration=50). Found earliest=1109 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 16:07:43,436][ERROR][4014970][experiments.py:run_experiment_from_to_file:752] XXX failed 2059 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1099, agent_id=43, malfunction_duration=50). Found earliest=1100 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 16:07:43,436][ERROR][4014970][experiments.py:run_experiment_from_to_file:752] XXX failed 2059 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 43 with malfunction ExperimentMalfunction(time_step=1099, agent_id=43, malfunction_duration=50). Found earliest=1100 for Waypoint(position=(76, 25), direction=1)
[2020-11-18 16:27:35,070][ERROR][4026320][experiments.py:run_experiment_from_to_file:752] XXX failed 2108 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=31, agent_id=18, malfunction_duration=50). Found earliest=32 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 16:27:35,070][ERROR][4026320][experiments.py:run_experiment_from_to_file:752] XXX failed 2108 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 18 with malfunction ExperimentMalfunction(time_step=31, agent_id=18, malfunction_duration=50). Found earliest=32 for Waypoint(position=(63, 60), direction=1)
[2020-11-18 16:57:02,821][ERROR][4038095][experiments.py:run_experiment_from_to_file:752] XXX failed 2140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=706, agent_id=50, malfunction_duration=50). Found earliest=707 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 16:57:02,821][ERROR][4038095][experiments.py:run_experiment_from_to_file:752] XXX failed 2140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 50 with malfunction ExperimentMalfunction(time_step=706, agent_id=50, malfunction_duration=50). Found earliest=707 for Waypoint(position=(19, 14), direction=3)
[2020-11-18 17:00:22,097][ERROR][3878721][experiments.py:run_experiment_from_to_file:752] XXX failed 1579 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:00:22,097][ERROR][3878721][experiments.py:run_experiment_from_to_file:752] XXX failed 1579 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:25:50,729][ERROR][4022955][experiments.py:run_experiment_from_to_file:752] XXX failed 2093 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:25:50,729][ERROR][4022955][experiments.py:run_experiment_from_to_file:752] XXX failed 2093 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:27:31,847][ERROR][3743657][experiments.py:run_experiment_from_to_file:752] XXX failed 1233 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:27:31,847][ERROR][3743657][experiments.py:run_experiment_from_to_file:752] XXX failed 1233 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 17:48:46,910][ERROR][4052079][experiments.py:run_experiment_from_to_file:752] XXX failed 2170 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 17:48:46,910][ERROR][4052079][experiments.py:run_experiment_from_to_file:752] XXX failed 2170 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-18 18:48:09,926][ERROR][4045959][experiments.py:run_experiment_from_to_file:752] XXX failed 2156 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 18:48:09,926][ERROR][4045959][experiments.py:run_experiment_from_to_file:752] XXX failed 2156 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 18:53:57,361][ERROR][4047072][experiments.py:run_experiment_from_to_file:752] XXX failed 2157 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 18:53:57,361][ERROR][4047072][experiments.py:run_experiment_from_to_file:752] XXX failed 2157 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 19:02:19,967][ERROR][4082026][experiments.py:run_experiment_from_to_file:752] XXX failed 2283 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 19:02:19,967][ERROR][4082026][experiments.py:run_experiment_from_to_file:752] XXX failed 2283 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 19:07:59,038][ERROR][4033200][experiments.py:run_experiment_from_to_file:752] XXX failed 2129 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 19:07:59,038][ERROR][4033200][experiments.py:run_experiment_from_to_file:752] XXX failed 2129 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 20:46:47,146][ERROR][4127360][experiments.py:run_experiment_from_to_file:752] XXX failed 2400 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=1529, agent_id=38, malfunction_duration=50). Found earliest=1530 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 20:46:47,146][ERROR][4127360][experiments.py:run_experiment_from_to_file:752] XXX failed 2400 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=1529, agent_id=38, malfunction_duration=50). Found earliest=1530 for Waypoint(position=(88, 22), direction=2)
[2020-11-18 21:21:31,769][ERROR][4138323][experiments.py:run_experiment_from_to_file:752] XXX failed 2427 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 21:21:31,769][ERROR][4138323][experiments.py:run_experiment_from_to_file:752] XXX failed 2427 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-18 22:21:32,589][ERROR][4023765][experiments.py:run_experiment_from_to_file:752] XXX failed 2095 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 22:21:32,589][ERROR][4023765][experiments.py:run_experiment_from_to_file:752] XXX failed 2095 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 22:21:58,735][ERROR][4117371][experiments.py:run_experiment_from_to_file:752] XXX failed 2375 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 22:21:58,735][ERROR][4117371][experiments.py:run_experiment_from_to_file:752] XXX failed 2375 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 22:32:04,575][ERROR][4029499][experiments.py:run_experiment_from_to_file:752] XXX failed 2121 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 22:32:04,575][ERROR][4029499][experiments.py:run_experiment_from_to_file:752] XXX failed 2121 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 23:37:20,531][ERROR][4138292][experiments.py:run_experiment_from_to_file:752] XXX failed 2426 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 23:37:20,531][ERROR][4138292][experiments.py:run_experiment_from_to_file:752] XXX failed 2426 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 23:39:24,352][ERROR][4140454][experiments.py:run_experiment_from_to_file:752] XXX failed 2431 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 23:39:24,352][ERROR][4140454][experiments.py:run_experiment_from_to_file:752] XXX failed 2431 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-18 23:54:00,389][ERROR][8067][experiments.py:run_experiment_from_to_file:752] XXX failed 2641 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-18 23:54:00,389][ERROR][8067][experiments.py:run_experiment_from_to_file:752] XXX failed 2641 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 00:07:11,163][ERROR][13284][experiments.py:run_experiment_from_to_file:752] XXX failed 2662 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 00:07:11,163][ERROR][13284][experiments.py:run_experiment_from_to_file:752] XXX failed 2662 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 00:10:32,837][ERROR][15535][experiments.py:run_experiment_from_to_file:752] XXX failed 2672 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=809, agent_id=38, malfunction_duration=50). Found earliest=810 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 00:10:32,837][ERROR][15535][experiments.py:run_experiment_from_to_file:752] XXX failed 2672 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=809, agent_id=38, malfunction_duration=50). Found earliest=810 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 00:37:45,768][ERROR][21055][experiments.py:run_experiment_from_to_file:752] XXX failed 2694 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-19 00:37:45,768][ERROR][21055][experiments.py:run_experiment_from_to_file:752] XXX failed 2694 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-19 01:40:45,814][ERROR][28959][experiments.py:run_experiment_from_to_file:752] XXX failed 2708 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 01:40:45,814][ERROR][28959][experiments.py:run_experiment_from_to_file:752] XXX failed 2708 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 02:09:55,885][ERROR][4139109][experiments.py:run_experiment_from_to_file:752] XXX failed 2429 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 02:09:55,885][ERROR][4139109][experiments.py:run_experiment_from_to_file:752] XXX failed 2429 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 02:21:25,399][ERROR][76254][experiments.py:run_experiment_from_to_file:752] XXX failed 2838 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-19 02:21:25,399][ERROR][76254][experiments.py:run_experiment_from_to_file:752] XXX failed 2838 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-19 03:20:44,939][ERROR][106500][experiments.py:run_experiment_from_to_file:752] XXX failed 2901 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-19 03:20:44,939][ERROR][106500][experiments.py:run_experiment_from_to_file:752] XXX failed 2901 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'float' and 'NoneType'
[2020-11-19 03:33:37,685][ERROR][16513][experiments.py:run_experiment_from_to_file:752] XXX failed 2676 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 03:33:37,685][ERROR][16513][experiments.py:run_experiment_from_to_file:752] XXX failed 2676 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 03:55:21,666][ERROR][127539][experiments.py:run_experiment_from_to_file:752] XXX failed 2944 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=531, agent_id=38, malfunction_duration=50). Found earliest=532 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 03:55:21,666][ERROR][127539][experiments.py:run_experiment_from_to_file:752] XXX failed 2944 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=531, agent_id=38, malfunction_duration=50). Found earliest=532 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 04:36:29,353][ERROR][22187][experiments.py:run_experiment_from_to_file:752] XXX failed 2697 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 04:36:29,353][ERROR][22187][experiments.py:run_experiment_from_to_file:752] XXX failed 2697 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 06:20:11,761][ERROR][189090][experiments.py:run_experiment_from_to_file:752] XXX failed 3128 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:20:11,761][ERROR][189090][experiments.py:run_experiment_from_to_file:752] XXX failed 3128 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:20:35,243][ERROR][189271][experiments.py:run_experiment_from_to_file:752] XXX failed 3129 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:20:35,243][ERROR][189271][experiments.py:run_experiment_from_to_file:752] XXX failed 3129 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:30:57,865][ERROR][193391][experiments.py:run_experiment_from_to_file:752] XXX failed 3140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:30:57,865][ERROR][193391][experiments.py:run_experiment_from_to_file:752] XXX failed 3140 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:49:42,853][ERROR][202356][experiments.py:run_experiment_from_to_file:752] XXX failed 3160 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:49:42,853][ERROR][202356][experiments.py:run_experiment_from_to_file:752] XXX failed 3160 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 06:50:21,049][ERROR][142797][experiments.py:run_experiment_from_to_file:752] XXX failed 2980 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 06:50:21,049][ERROR][142797][experiments.py:run_experiment_from_to_file:752] XXX failed 2980 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 07:47:36,489][ERROR][225702][experiments.py:run_experiment_from_to_file:752] XXX failed 3216 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=318, agent_id=38, malfunction_duration=50). Found earliest=319 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 07:47:36,489][ERROR][225702][experiments.py:run_experiment_from_to_file:752] XXX failed 3216 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data agent 38 with malfunction ExperimentMalfunction(time_step=318, agent_id=38, malfunction_duration=50). Found earliest=319 for Waypoint(position=(88, 22), direction=2)
[2020-11-19 07:48:01,662][ERROR][223958][experiments.py:run_experiment_from_to_file:752] XXX failed 3212 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-19 07:48:01,662][ERROR][223958][experiments.py:run_experiment_from_to_file:752] XXX failed 3212 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'float'
[2020-11-19 07:51:25,024][ERROR][225721][experiments.py:run_experiment_from_to_file:752] XXX failed 3217 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 07:51:25,024][ERROR][225721][experiments.py:run_experiment_from_to_file:752] XXX failed 3217 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data Cannot take a larger sample than population when 'replace=False'
[2020-11-19 08:24:28,226][ERROR][236371][experiments.py:run_experiment_from_to_file:752] XXX failed 3243 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-19 08:24:28,226][ERROR][236371][experiments.py:run_experiment_from_to_file:752] XXX failed 3243 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2020-11-19 10:32:36,685][ERROR][16982][experiments.py:run_experiment_from_to_file:752] XXX failed 2680 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 10:32:36,685][ERROR][16982][experiments.py:run_experiment_from_to_file:752] XXX failed 2680 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 12:19:05,625][ERROR][236149][experiments.py:run_experiment_from_to_file:752] XXX failed 3242 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 12:19:05,625][ERROR][236149][experiments.py:run_experiment_from_to_file:752] XXX failed 3242 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 12:43:09,690][ERROR][10402][experiments.py:run_experiment_from_to_file:752] XXX failed 2650 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 12:43:09,690][ERROR][10402][experiments.py:run_experiment_from_to_file:752] XXX failed 2650 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 14:01:45,624][ERROR][111873][experiments.py:run_experiment_from_to_file:752] XXX failed 2912 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 14:01:45,624][ERROR][111873][experiments.py:run_experiment_from_to_file:752] XXX failed 2912 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 14:03:21,748][ERROR][245037][experiments.py:run_experiment_from_to_file:752] XXX failed 3254 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 14:03:21,748][ERROR][245037][experiments.py:run_experiment_from_to_file:752] XXX failed 3254 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 17:28:56,296][ERROR][132904][experiments.py:run_experiment_from_to_file:752] XXX failed 2956 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
[2020-11-19 17:28:56,296][ERROR][132904][experiments.py:run_experiment_from_to_file:752] XXX failed 2956 PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/data 
